language: python
python:
- 3.5
- 3.6
- 3.7-dev
before_install:
- pip install "pytest>=3.6"
- pip install pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
    python: 3.7-dev
  password:
    secure: QlzBkXw/hOf/MyRPiOxHE0cqZ1TTX9W2Q6JcKtAFRSiJTjLMpu6fUgu50e6eAi6mcFihuLscFrO0C+wS49NSbn88iTvKqJyHR6wIDvYWUfM8f/OiwwMqU8yyWhmxjapAFrvzaBeIr+zXqsgEqg65QhV1qs5HzWbN44UnOKkKCpXxaqHUBuKF9rX1pZfHtG2TzWh0D1Vs0Z6GU9+951i0wv/f4jEeYsx6/EmPFUlbXI7o44LZzNoqxVTFzuVk3/ywS+wrr/3Cq32ol3QBEncxfVBCj6+YKCOyzzX4gO+STcYmBTk4N/qr5eMlWNVKY++x80SA/ZJUVQ2jHtpjDEDH8T6N1psROHQxJPWKXqv1VsZfm45F74t3TKhFRiXzAJgnBmWIccfAhkluh6TDZOak5sivskDbd43NsFOnbs4mwhc2yUFX2JCpG4L76eC0MB/I6GwO3M/7exB3O9liRJOPCMm5VEdLt0zCZfWXqIeaFZA5fe6EuKGkQSPyEAGPiJTWpab7saY+1r0LlsWMa5GNrpcLeoOGUeYwGWTSO6c097lzZNVN6swuuOXUzcFm2CnvNkvni3mKlNlWbJj6/hgNldKILA14mgJIBcBpc2Ca0Puss6mGMVlKeswuD24QbcHlpr87Smcnd46pYsRG45/+MhCu16hqykXMgkxEM3RK9Cs=
